name: DataLog
main: uk.co.oliwali.DataLog.DataLog
author: oliverw92
version: 1.0.0
database: true
commands:
  datalog:
    description: Advanced Data Logging
    aliases: dl
    usage: /<command> help