name: HawkEye
main: uk.co.oliwali.HawkEye.HawkEye
author: oliverw92
version: 1.4.0
description: Advanced Data Logging
softdepend: [WorldEdit,Spout]
commands:
  HawkEye:
    description: Advanced Data Logging
    aliases: dl
    usage: /<command> help
